### PR TITLE
General update to Project/Repository

### PR DESCRIPTION
**Pull request by gep13**
@vhatsura I have made a few suggested changes in this PR.  The main one being the inclusion of the NuGet Metadata, which is recommended by the NuGet Team.  Please let me know if you have any questions about the changes in this PR.

### CODE REVIEW

**Comment by gep13** [comment]
@vhatsura thank you for taking the time to review and merge this.  Are you planning on creating a new release to push to NuGet.org, so that the new metadata will make its way to the site?

**Comment by vhatsura** [comment]
@gep13, I pushed new tag a few moments ago. New package will be available on nuget.org soon.

**Comment by gep13** [comment]
@vhatsura thank you for doing that, I really appreciate it!

**Comment by gep13** [comment]
@vhatsura another question while I have you... would you be interested in moving this repository under the Cake Contrib Organisation on GitHub? You would still be the main maintainer of the addin, with full access rights to the repository, it would just live under the Org on GitHub. This is something we advice, but don’t insist on for addins, as it allows for other people to help out with the maintenance of an addin, if required.

**Comment by vhatsura** [comment]
@gep, I appreciate for interest from your side, however, I don't have plans with transfer addin to cake organization. If I change my mind I will contact you.
Thanks a lot for your work.

**Comment by gep** [comment]
@gep13 comment above is for you.

**Comment by gep13** [comment]
@vhatsura thank you for confirming.  I won't bother you with this question again.

**Pull request merged**
